import { test, expect } from '@playwright/test';
import { publisherToken } from '../helpers.js';

test('desktop rail, chat columns and login stay within the viewport', async ({ page }) => {
  await page.setViewportSize({ width:1280, height:800 });
  await page.goto('/');
  await expect(page.locator('#locked')).toBeVisible();
  const login = await page.locator('#locked').boundingBox();
  expect(login.width).toBeLessThanOrEqual(480);
  expect(Math.abs(login.x + login.width / 2 - 640)).toBeLessThan(2);
  await page.screenshot({ path:'test-results/desktop-login.png' });
  await page.locator('#loginUsername').fill('admin');
  await page.locator('#loginPassword').fill('test-password-123');
  await page.locator('#loginForm button').click();
  await expect(page.locator('#settings')).toBeVisible();
  await page.locator('#token').fill(publisherToken);
  await page.locator('#savePublisher').click();
  await page.locator('.rail-nav [data-rail-tab="chat"]').click();
  await expect(page.locator('#chat')).toBeVisible();
  const rail = await page.locator('.app-rail').boundingBox();
  const list = await page.locator('.chat-list').boundingBox();
  expect(rail.width).toBe(230);
  expect(list.width).toBe(300);
  expect(list.x).toBe(rail.x + rail.width);
  await expect(page.locator('.rail-bot-name')).toBeVisible();
  await page.locator('#inboxStatus').evaluate(node => { node.textContent = '已有外部 webhook；确认旧服务停用后可接管 '.repeat(4); });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(1280);
  expect(await page.locator('.app-rail').evaluate(node => node.scrollWidth)).toBeLessThanOrEqual(rail.width);
  await page.screenshot({ path:'test-results/desktop-chat.png' });
  await page.locator('.rail-nav [data-rail-tab="editor"]').click();
  expect((await page.locator('.app-rail').boundingBox()).width).toBe(230);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(1280);
  await page.screenshot({ path:'test-results/desktop-editor.png' });
  await page.setViewportSize({ width:390, height:844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
