import {test,expect} from '@playwright/test';
import {signedData,publisherToken} from '../helpers.js';
test('user folds, complete selected list, blue controls and deliberate editing',async({page,request})=>{
  const headers={'x-telegram-init-data':signedData()};
  await request.post('/api/publisher',{headers,data:{token:publisherToken}});
  await page.route('https://telegram.org/js/telegram-web-app.js',r=>r.fulfill({contentType:'application/javascript',body:`window.Telegram={WebApp:{initData:${JSON.stringify(signedData())},ready(){},expand(){}}};`}));
  const users=[{telegram_id:'80001',display_name:'用户甲',active:1},{telegram_id:'80002',display_name:'用户乙',active:1}];
  await page.route('**/api/players?*',r=>{const q=new URL(r.request().url()).searchParams.get('q');return r.fulfill({json:{rows:q?users.slice(1):users,total:q?1:2}});});
  await page.route('**/api/players/ids',r=>r.fulfill({json:{rows:users}}));
  await page.goto('/');await expect(page.locator('#workspace')).toBeVisible();
  await expect(page.locator('#message .ql-editor')).toHaveAttribute('contenteditable','false');
  await page.locator('#toggleWriting').click();await page.locator('#message .ql-editor').fill('正文');
  await page.locator('#toggleWriting').click();await expect(page.locator('#message .ql-editor')).toHaveAttribute('contenteditable','false');
  await page.locator('[data-tab=players]').click();await expect(page.locator('[data-tab=players]')).toHaveText('用户');
  await expect(page.locator('#playerList')).toBeHidden();await page.locator('#usersPanel summary').click();
  await page.locator('[data-player-id="80001"]').check();await page.locator('[data-player-id="80002"]').check();
  await expect(page.locator('#playerSelectionCount')).toContainText('2 人');
  await page.locator('#playerSearch').fill('乙');await page.locator('#refreshPlayers').click();
  await page.locator('#selectedPanel summary').click();await expect(page.locator('#selectedPlayerList .list-row')).toHaveCount(2);
  await page.locator('[data-unselect="80001"]').click();await expect(page.locator('#playerSelectionCount')).toContainText('1 人');
  await page.locator('#selectAllPlayers').click();await expect(page.locator('#selectedPlayerList .list-row')).toHaveCount(2);
  await page.locator('[data-tab=editor]').click();await page.locator('#selectedPlayersHint').click();await expect(page.locator('#selectedPlayerList .list-row')).toHaveCount(2);
  const styles=await page.locator('#syncPlayers,#importPlayers,#refreshPlayers,#selectAllPlayers,#clearPlayers').evaluateAll(ns=>ns.map(n=>({color:getComputedStyle(n).color,bg:getComputedStyle(n).backgroundColor,r:getComputedStyle(n).borderRadius})));
  expect(new Set(styles.map(s=>JSON.stringify(s))).size).toBe(1);
  await page.evaluate(()=>{window.scrollTo(0,0);document.getElementById('toast').hidden=true;});
  await page.screenshot({path:'test-results/users-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1000,height:850});await page.screenshot({path:'test-results/users-desktop.png',fullPage:true});
});

test('links require explicit edit and successful broadcasts can be edited and deleted separately',async({page,request})=>{
  const headers={'x-telegram-init-data':signedData()};
  await request.post('/api/publisher',{headers,data:{token:publisherToken}});
  await page.route('https://telegram.org/js/telegram-web-app.js',r=>r.fulfill({contentType:'application/javascript',body:`window.Telegram={WebApp:{initData:${JSON.stringify(signedData())},ready(){},expand(){}}};`}));
  await page.goto('/');await page.locator('#editLink').click();await page.locator('#linkText').fill('测试链接');await page.locator('#linkUrl').fill('https://t.me/example');await page.locator('#saveLink').click();
  await page.locator('#message .ql-editor a').click();await expect(page.locator('#linkDialog')).toBeHidden();
  await page.locator('#editLink').click();await expect(page.locator('#linkUrl')).toHaveValue('https://t.me/example');await page.locator('#cancelLink').click();
  await request.post('/api/players/import',{headers,multipart:{file:{name:'users.csv',mimeType:'text/csv',buffer:Buffer.from('ID,昵称,telegram_id\n1,测试用户,80001\n')}}});
  const created=await request.post('/api/broadcasts',{headers,data:{name:'操作回归',delta:{ops:[{insert:'原消息\n'}]},buttons:[],playerIds:['80001']}});expect(created.ok()).toBeTruthy();const item=await created.json();
  await expect(async()=>{const r=await(await request.get(`/api/broadcasts/${item.id}`,{headers})).json();expect(r.deliveries[0].status).toBe('SUCCESS');}).toPass();
  await page.locator('[data-tab=players]').click();await page.locator('#broadcastPanel summary').click();await page.locator(`[data-sent-broadcast="${item.id}"]`).click();
  await page.locator('#selectSent').click();await page.locator('[data-load-sent]').first().click();
  await expect(page.locator('#sentEditLink')).toBeVisible();await expect(page.locator('#sentBodyEmoji')).toBeVisible();await expect(page.locator('#sentAddButton')).toBeVisible();
  await page.locator('#sentBodyEmoji').click();await page.locator('#sentPack').fill('test_pack');await page.locator('#sentLoadPack').click();await page.locator('#sentEmojiPicker summary').click();await page.locator('#sentEmojiGrid .emoji-choice').first().click();await expect(page.locator('#sentBody .ql-editor .custom-emoji')).toHaveCount(1);
  await page.locator('#sentBody .ql-editor').fill('点击这里');await page.locator('#sentBody .ql-editor').selectText();await page.locator('#sentEditLink').click();await page.locator('#sent-linkText').fill('点击这里');await page.locator('#sent-linkUrl').fill('https://t.me/edited');await page.locator('#sent-saveLink').click();await expect(page.locator('#sentBody .ql-editor a')).toHaveAttribute('href','https://t.me/edited');
  await page.locator('#sentAddButton').click();await page.locator('[data-sent-button-field="url"]').last().fill('https://t.me/button');await page.locator('[data-sent-emoji="0"]').click();await page.locator('#sentEmojiGrid .emoji-choice').nth(1).click();await expect(page.locator('[data-sent-emoji="0"]')).toContainText('更换专属表情');
  await page.locator('#sentBody .ql-editor').fill('更新消息');
  page.once('dialog',d=>d.accept());await page.locator('#applySent').click();await expect(page.locator('#sentProgress')).toContainText('成功 1');await expect(page.locator('#sentRecipients')).toContainText('已编辑');
  await page.locator('#selectSent').click();page.once('dialog',d=>d.accept());await page.locator('#deleteSent').click();await expect(page.locator('#sentRecipients')).toContainText('已删除');
  await page.locator('#closeSent').click();await page.locator(`[data-sent-broadcast="${item.id}"]`).click();await expect(page.locator('[data-sent-id]')).toBeDisabled();
  await expect(page.locator('#message .ql-editor')).toContainText('测试链接');
});
