#!/usr/bin/env bash
set -euo pipefail
PATH="/c/Program Files/Git/usr/bin:$PATH"
BASE="$(dirname "$0")"
DEST="${1:?pass a target copy directory}"
mkdir -p "$DEST/"
cp "$BASE/BASELINE.index.html" "$DEST/index.html"
mkdir -p "$DEST/"
cp "$BASE/BASELINE.package.json" "$DEST/package.json"
mkdir -p "$DEST/"
cp "$BASE/BASELINE.package-lock.json" "$DEST/package-lock.json"
mkdir -p "$DEST/src"
cp "$BASE/BASELINE.src.main.js" "$DEST/src/main.js"
mkdir -p "$DEST/"
cp "$BASE/BASELINE..gitignore" "$DEST/.gitignore"
rm -f "$DEST/src/desktop-bridge.js"
rm -f "$DEST/src/desktop.css"
rm -f "$DEST/desktop/README.md"
rm -f "$DEST/desktop/src-tauri/Cargo.toml"
rm -f "$DEST/desktop/src-tauri/Cargo.lock"
rm -f "$DEST/desktop/src-tauri/build.rs"
rm -f "$DEST/desktop/src-tauri/src/lib.rs"
rm -f "$DEST/desktop/src-tauri/src/main.rs"
rm -f "$DEST/desktop/src-tauri/tauri.conf.json"
rm -f "$DEST/desktop/src-tauri/capabilities/default.json"
rm -f "$DEST/desktop/src-tauri/icons/icon.svg"
rm -f "$DEST/desktop/src-tauri/icons/icon.png"
rm -f "$DEST/desktop/src-tauri/icons/icon.ico"
